import { Injectable, Logger } from "@nestjs/common";
import { PrismaService } from "@/core/prisma";

@Injectable()
export class DatabaseService {
  private readonly logger = new Logger(DatabaseService.name);

  constructor(public readonly prisma: PrismaService) {}

  /**
   * Typed sales query — uses ONLY Prisma's safe findMany / groupBy / aggregate.
   * Absolutely NO raw SQL strings.
   */
  async querySales(params: {
    where?: Record<string, unknown>;
    groupBy?: "region" | "category";
    orderBy?:
      | { amount?: "desc" | "asc" }
      | { quantity?: "desc" | "asc" }
      | { saleDate?: "desc" | "asc" };
    limit?: number;
  }): Promise<Record<string, unknown>[]> {
    const { where = {}, groupBy, orderBy, limit } = params;

    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const prismaWhere: any = {};
    if (where.region) prismaWhere.region = String(where.region);
    if (where.category) prismaWhere.category = String(where.category);
    if (where.saleDate) prismaWhere.saleDate = where.saleDate;
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    const prismaOrderBy: any = orderBy ?? { saleDate: "desc" };

    if (groupBy) {
      // Aggregate query with groupBy
      // eslint-disable-next-line @typescript-eslint/no-explicit-any
      const result: any = await (this.prisma.sales.groupBy as any)({
        by: [groupBy],
        where: prismaWhere,
        _sum: { amount: true, quantity: true },
        _count: { id: true },
        orderBy: prismaOrderBy,
        take: limit,
      });

      return result.map((r: any) => ({
        [groupBy]: r[groupBy],
        totalAmount: r._sum.amount ?? 0,
        totalQuantity: r._sum.quantity ?? 0,
        orderCount: r._count.id,
      }));
    }

    // Plain findMany
    const rows = await this.prisma.sales.findMany({
      where: prismaWhere,
      orderBy: prismaOrderBy,
      take: limit,
    });

    return rows.map((r) => ({
      id: r.id,
      productName: r.productName,
      category: r.category,
      amount: Number(r.amount),
      quantity: r.quantity,
      region: r.region,
      saleDate: r.saleDate.toISOString(),
    }));
  }

  /**
   * Execute a validated SELECT query.
   *
   * Security: The SQL string must have already passed SqlAgent.assertSafe()
   * (SELECT-only, no DDL keywords, double-quoted identifiers) before reaching here.
   * $queryRawUnsafe is unavoidable here because the SQL structure (columns, tables,
   * WHERE clauses) is dynamically generated by the LLM and cannot be expressed
   * via Prisma's typed parameterised queries.
   */
  async executeQuery(sql: string): Promise<unknown[]> {
    try {
      const result = await this.prisma.$queryRawUnsafe(sql);
      return result as unknown[];
    } catch (error) {
      this.logger.error(
        `Query execution failed: ${error instanceof Error ? error.message : String(error)}`,
      );
      throw error;
    }
  }

  /**
   * Schema introspection — uses a hard-coded query with no user input,
   * so $queryRawUnsafe is safe here.
   */
  async getSchema(): Promise<unknown> {
    const tables = await this.prisma.$queryRawUnsafe(`
      SELECT table_name, column_name, data_type, is_nullable
      FROM information_schema.columns
      WHERE table_schema = 'public'
      ORDER BY table_name, ordinal_position
    `);
    return tables;
  }
}
